language: cpp
os: linux
compiler: gcc

addons:
  apt:
    packages:
    - lcov
    - libeigen3-dev

script:
- cd 3PL
- bash build_3PL.sh
- cd ..
- cd AutoDiff
- bash config.sh
- cd ..

after_success:
- cd AutoDiff 
- bash coverage.sh
# Uploading to CodeCov
- bash <(curl -s https://codecov.io/bash) -f ./coverage/AD_COV.info || echo "Codecov did not collect coverage reports -- AD"
- cd ..
- cd Dual
- bash <(curl -s https://codecov.io/bash) -f ./coverage/DUAL_COV.info || echo "Codecov did not collect coverage reports -- DUAL"
- cd ..
